---
title: "Predicate Logic"
---

In this chapter we extend propositional logic to another logic with more expressive power. In this section, we introduce predicate logic, and in a future section we will extend it to first-order logic.

# Predicates

There is a certain sort of logic which cannot be captured by propositional logic. Take for instance "Tabby is an orange cat, and Mr. Mewsieur is a cat but is not orange". Tabby and Mr. Mewsieur share the property of being a cat, and propositional logic cannot capture this. Therefore we will make symbols for objects and symbols for properties, and have a way of talking about which objects have which properties.

For instance we could write $t, m$ for the two objects, Tabby and Mr. Mewsieur respectively. We will write $O, C$ for the properties of being orange or being a cat, respectively. Then the above sentence becomes the symbolic expression

> $O(t)\land C(t) \land C(m)\land\neg O(m)$

Of course we don't abandon the work we did with propositional logic! We still have the propositional operators. But rather than applying them to simple propositional variables, the propositional variables are themselves decomposed into predicate and object.

We will generally use lower-case letters for objects, and these are called **constant symbols**, because what they refer to is some constant object. We will use upper-case letters for predicates, and these are called **predicate symbols**.

::: {.callout-important title="Predicates Two and Three" appearance="minimal"}
Use predicates and objects to symbolically represent the sentence "Two is even but three is odd."
:::

# Relations

Now predicates are pretty straight-forward. But often we don't just want to say that some one object either has or doesn't have some property. Often we want to talk about multiple objects in relation to each other. For instance, if we wanted to express that 2 is less than 3, we couldn't do this merely with predicates.

Therefore we may write $L$ as a two-place relation symbol, which we understand to mean "less-than". If we write symbols $t_w,t_h$ to denote two and three respectively, then the sentence "two is less than three" is represented symbolically as

> $L(t_w,t_h)$

::: {.callout-important title="Three Place Exercise" appearance="minimal"}
The extension to three-place predicates is natural. Come up with a three-place relation and three different constant symbols, in order to express: "Point $P$ is in-between points $Q$ and $R$."
:::

Relations are theoretically quite similar to predicates, just holding between more than one object. But like a predicate, they describe objects and they may hold or not. Therefore we write them with upper-case letters, and call these **relation symbols**.

We will call all constant, predicate, and relation symbols **nonlogical symbols**.[^1]

[^1]: This does not mean that the symbols are in any way illogical. It just means that they do not have their truth-value determined *merely* by logic.

The expressions $O(t)$ and $L(t_w,t_h)$ are propositions -- they do express statements which are either true or false. Moreover, we can form complex propositions with them, like $O(t)\to\neg L(t_w,t_h)$. We will call propositions with no logical operators (for example, $O(t)$) **simple propositions**. Propositions with logical operators ($\neg O(t)$) are called **complex propositions**.

# Structures

## Interpretation

We analyzed the possibilities for propositional variables with variable evaluations, or equivalently, a truth-table. For a more expressive syntax, though, we should have a new way of assessing the expressions. Let's first make an example language.

Consider a language for natural numbers. To keep things simple, we will take a very small language with just three constant symbols, $a,b,c,d$. These will be *intended* to refer to the numbers 1, 2, and 3.[^2] However, part of the job of the structure is to make this interpretation "official". We will also have a two-place relation symbol *L*.

[^2]: A keen-eyed observer will note that there are four symbols and three numbers -- why the mismatch? As you will see shortly, this is intentional.

Now that we know the language, we can talk about a structure for the language. We will write this structure as $\mathcal S$. To express that this $\mathcal S$ interprets $a$ as the number $1$, we will write $a^{\mathcal S}$ = 1. Likewise $b^{\mathcal S}=2,c^{\mathcal S}=3,d^{\mathcal S}=3$ express the interpretation of $b$ as $2$ and $c$ and $d$ as $3$. $\mathcal S$ also interprets the symbol $L$ as the less-than relation. It is common to express this last fact by the following set equality.

$$
L^{\mathcal S} = \{(1,2),(1,3),(2,3)\}
$$

If you've never seen this before it's likely confusing. What this says is that $(1,2)$ is in the relation, that is to say, $(1,2)\in L^{\mathcal S}$. And what *this* means is that 1 is related to 2.

Continuing likewise, it says that 1 relates to 3 and 2 relates to 3. In total, this expresses the less-than relation among the numbers 1, 2, and 3!

::: {.callout-important title="Love Triangle Relation" appearance="minimal"}
Using the same language as above, write down a structure which interprets $a$ as the person named Adam, $b$ is Becky, $c$ is Carla, $d$ is Dale, and $L$ is the "loves" relation. Write down a structure which corresponds to: Adam loves Becky, Becky loves Carla, Carla loves nobody, and Dale loves everybody.
:::

If we added to the example above, a predicate $E$ meant to represent the even numbers, then we would have $E^{\mathcal S}=\{2\}$. This shows that, for a predicate, its interpretation is the set of elements which have the property.

Now because we are able to talk about objects, it will be useful to introduce a new symbol into our language: The equality symbol. This will allow us to write, for example, the propositions $c=d$ and $a\ne b$, both of which are true in this particular structure (but not in the structure described in the exercise above, "Love Triangle Relation").

## Evaluation

Now a structure should not merely interpret. It should also evaluate, which is to say, tell us whether a given proposition is true or false. If we take the example above, whereby

$$
a^{\mathcal S}=1,b^{\mathcal S}=2,c^{\mathcal S}=3,L^{\mathcal S}=\{(1,2),(1,3),(2,3)\}
$$

then we should have that $(L(a,b))^{\mathcal S}=T$ since $a$ denotes 1 and $b$ denotes 2, and $L$ is the less-than relation. Since 1 and 2 stand in the less-than relation, this proposition is true. On the other hand, we should have $(L(b,a))^{\mathcal S}=F$.

The technical definition of the evaluation of a simple proposition of a two-place relation is: Let $R$ be any two-place relation symbol and $a,b$ any two constant symbols in the language. Then $(R(a,b))^{\mathcal S} = T$ if and only if $(a^{\mathcal S},b^{\mathcal S})\in R^{\mathcal S}$.  

It may help to see this definition "in action".  In the example above, $(L(a,b))^{\mathcal S}=T$ because $(a^{\mathcal S},b^{\mathcal S}) = (1,2)$ and also $L^{\mathcal S}=\{(1,2),(1,3),(2,3)\}$.  Therefore we do have the relation $(a^{\mathcal S},b^{\mathcal S})\in L^{\mathcal S}$ which is why we can evaluate

$$
(L(a,b))^{\mathcal S}=T
$$

On the other hand $(L(b,a))^{\mathcal S}=F$ because $(b^{\mathcal S},a^{\mathcal S})=(2,1)\not\in L^{\mathcal S}$.  

::: {.callout-important title="Love Triangle Evaluation" appearance="minimal"}
Using again the structure that you used in the previous exercise "Love Triangle Relation", decide whether the following propositions are true.

$$
L(a,b),\quad L(b,a),\quad L(c,d)\to\neg L(d,c)
$$
:::

Of course we have a simple rule for evaluating equality.  If $a,b$ are any two constant symbols then $(a=b)^{\mathcal S}=T$ if and only if $a^{\mathcal S}=b^{\mathcal S}$.  