---
title: "Axiom Systems"
---

Finally we can say something about axiomatic systems. In order to discuss this, we should have in mind a few examples of axiomatic systems.

Note that I will present these systems at a relatively introductory and intuitive level -- we will not say anything very detailed, about how to use them, or what they mean.

# Examples of Axiom Systems

## Euclidean Geometry

Euclidean geometry is the axiom system which describes most of the familiar ideas of geometry. It is made from the following list of axioms.[^1]

[^1]: These are largely adapted from Hartshorne's *Beyond Euclid* textbook.

1.  There are some three points which are not colinear.
2.  For any two points there is a unique line which runs through them.
3.  For any line it contains at least two points.
4.  A line segment can be prolonged indefinitely.
5.  For any two points there is a circle which is centered on one of the points and passing through the other.
6.  For any line and point not on the line, there exists a line parallel to the first line, which runs through the point.

Here is an example proposition which can be proved from them:

::: {.callout-tip title="Two Lines, One Intersection" appearance="minimal"}
Theorem: Any two lines intersect in at most one point.

Proof: Suppose for contradiction that some two distinct lines, $\ell_1,\ell_2$, intersect at some two distinct points, $P_1,P_2$. Then by defintion, $P_1\in \ell_1$ and $P_2\in \ell_1$, and also $P_1\in\ell_2$ and $P_2\in\ell_2$.[^2]

By axiom (2.) applied to the facts $P_1\in\ell_1,P_2\in\ell_1$, there is a *unique* line running through $P_1$ and $P_2$, and so it must be $\ell_1$. This just means that if any other line runs through these two points, then it must equal $\ell_1$.

But since we also have $P_1\in\ell_2,P_2\in\ell_2$, then from what we said immediately above, $\ell_2$ must be the same line as $\ell_1$.

But this is a contradiction, since our assumption was $\ell_1\ne\ell_2$ but we have now derived $\ell_1=\ell_2$.

Since the assumption that "there are some two lines which intersect at some two points" led to a contradiction, then therefore this must not be true. That is to say, we have proved that any two distinct lines must intersect in at most one point.

$\Box$
:::

[^2]: Note that this uses set membership notation, and this is no accident. While you should feel free to read "$P_1\in\ell_1$" as "point $P_1$ is on line $\ell_1$" -- it is also correct to say $P_1$ is an element of the set $\ell_1$, because we will understand lines to be sets of points.

Euclidean geometry just is the set of all "logical consequences" of the axioms. That is to say, Euclidean geometry is the set of propositions which are entailed by the set of axioms.

## Peano Arithmetic

Here are the axioms of Peano arithmetic:

1.  0 is a natural number.
2.  Every natural number has a successor.
3.  If two numbers share the same successor then they are the same number.
4.  0 is not the successor of any number.
5.  Induction is valid.

I'm sure that especially axiom number 5 seems provocative! We will have much more to say about it in the chapter on [First Order Logic](..\fol\pred.html), but for now I just want to show the various axioms systems at an introductory level. So we won't currently worry about exactly what is meant by these.

Here is a very simple example theorem.

::: {.callout-tip title="Two Successors" appearance="minimal"}
Theorem: If two numbers have different successors, then they are different numbers.

Proof: Suppose $m,n$ are two natural numbers and $S(m)\ne S(n)$.

Suppose for contradiction that $m=n$. Then $S(m)=S(n)$ but this contradicts $S(m)\ne S(n)$.

Therefore $m\ne n$.

$\Box$
:::

## Real Numbers

1.  Addition and multiplication are operations on real numbers. The set of real numbers is closed under this operation.[^3]
2.  Both operations are associative and commutative.
3.  Addition has an identity element, written as $0$. The fact that $0$ is an identity element, means that for any other real number, $x$, the equality $0+x=x=x+0$ holds.
4.  Every real number has an "additive inverse". If $x$ is any real number, then we write its additive inverse as $-x$. The fact that $-x$ is the additive inverse of $x$, means that their sum is the identity. I.e.\
    \$\$\
    -x+x = 0\
    \$\$
5.  Every real number other than $0$ has a multiplicative inverse. If $x$ is a nonzero real number then we write its multiplicative inverse as $x^{-1}$ or $1/x$. Being the multiplicative inverse means that $x$ and $x^{-1}$ multiply to the identity -- but notice that this time the identity is $1$!\
    \$\$\
    x\^{-1}\\cdot x = 1\
    \$\$
6.  Multiplication distributes over addition: For any three real numbers $x,y,z$ we have\
    \$\$\
    x(y+z)=xy+xz\
    \$\$

[^3]: Saying that "the real numbers are closed under addition", for example, means that if you add two real numbers, then the result is again a real number.

::: {.callout-tip title="Real Number Demo" appearance="minimal"}
Theorem: Zero times any number is zero.

Proof: Let $x$ be any real number. Then the following chain of equations holds.

$$
0x = (-1+1)x = (-1)x + 1x = (-1)x + x
$$

The first equation is true because $0=-1+1$, which is an instance of axiom 4. The second equaiton is an application of axiom 6. The third equation is an instance of axiom 3.

I claim, as a lemma, that $(-1)x=-x$. We will see the proof of this lemma in a later section, but for now we take it for granted. Therefore we have

$$
0x = -x+x = 0
$$

where the first equation is due to the lemma, and the second equation is an instance of axiom 4.

$\Box$
:::

## ZFC

ZFC is perhaps "the big one" because it can be taken as a foundation for almost all of mathematics. However, the axioms can be quite complex and abstract, and therefore it doesn't make much sense to present them until after we have discussed first-order logic in the next chapter. First-order logic will then equip us with some of the language and concepts that we will need to make sense of these axioms.

# Sets of Propositions

An **axiom system** is really just any set of axioms, which really just means any set of propositions.[^4] Our hope, however, is to take this set of propositions to be as small as possible. If done right, we will not lose anything, because all of the true propositions will become "consequences" of the axioms.

[^4]: This is not entirely accurate. More formally, we take an axiom system to be any any "decidable" set of propositions. However, saying exactly what "decidable" means is difficult and so I will avoid the issue. Just know that every set of axioms that we will discuss in this textbook are decidable sets. Therefore, under just about anyone's definition, they count as axioms.

The **theory** of an axiom system is the set of all of its consequences. More formally, if $A$ is any set of axioms, then the theory of $A$ is

$$
\text{Th}(A) = \{ \alpha: A\vDash \alpha\}
$$

If $\alpha\in\text{Th}(A)$ then we call $\alpha$ a **theorem**. Note that $\alpha$ is a theorem of $A$ if and only if $\alpha$ is entailed by $A$, and this fact deserves no proof because it is immediately from definitions.

::: {.callout-important title="Theory Monotonicity" appearance="minimal"}
Prove that for any axiom system $A$,

$$ 
A\subseteq \text{Th}(A)
$$
:::

::: {.callout-important title="Make a Theory Example" appearance="minimal"}
Make an example of an axiom system and theory, such that its theory contains a proposition which the axioms system does not. Also make an example of an axiom system, such that it has all the same propositions as its theory.
:::

It turns out that, for propositional logic, there is no difference between $A\vDash \alpha$ and $A\vdash \alpha$. That is to say $A\vDash \alpha$ if and only if $A\vdash \alpha$.

The fact that $A\vdash\alpha$ implies $A\vDash\alpha$ is called the **soundness** of propositional logic. It effectively "says" that if there is a proof, then you can trust it. That is to say, proofs guarantee truth.

The fact that $A\vDash\alpha$ implies $A\vdash \alpha$ is called the **completeness** of propositional logic. It effectively says that everything true has a proof.

We could prove the soundness and completeness for propositional logic. However, this would not significantly help us to understand how to do mathematics, which is the goal of the textbook. It is, however, worth knowing about soundness and completeness.

In particular, it is interesting because there are other interesting logical systems. None of them fail soundness, because that would make the system entirely useless. The whole point of a proof is to guarantee truth! But some of them will be important, useful, and yet fail completeness. That is to say, there are some systems with some true propositions, for which a proof is not possible.