---
title: "Ancient Greece"
---

The study of logic has two origins, philosophy and geometry. In many places throughout the world, people tried to establish rules of logic in order to clarify and resolve philosophical and political arguments.

However, in ancient Greece, there was a rather different context in which logic was studied.

# The Logic Network

Over several centuries, the cultures of Greece, Babylon, Egypt, and more, all had discovered thousands of geometric ideas and theorems.[^1] For instance, it was known that

[^1]: Of course other civilizations also had highly developed mathematical knowledge. Especially the ancient Hindus seem to have developed a large body of knowledge independently, and they studied logic with some depth. However, for whatever reason, they never developed axiomatic mathematics -- and for that reason, they are not the focus of our story here.

-   The interior angles of a triangle sum to 180 degrees.

-   The Pythagorean theorem, relating the side lengths of a right triangle.

-   For any line and point not on the line, there is a parallel line through the point.

    {{< video images/media/videos/images/720p30/LinePointParallel.mp4 >}}

They knew much more besides.

But it sometimes turned out that they would know fact *A* which implied some other fact *B* -- but then later they would discover that, also, fact *B* implies fact *A*! For example consider

::: {.callout-note title="Fact A" appearance="minimal"}
For every line $\ell$ and point $P$ not on $\ell$, there is a line $\ell'$ passing through $P$ parallel to $\ell$.
:::

::: {.callout-note title="Fact B" appearance="minimal"}
For every triangle $T$ the sum of its interior angles is $180^\circ$.
:::

We will see in a few chapters from now, that it is actually possible to prove Fact B from Fact A, and we can prove Fact A from Fact B.[^2]

[^2]: Other facts are also needed -- the "Euclidean postulates".

This inspires the question: Which fact is more foundational? If we are to share a common language and understanding of mathematics, we should try to agree upon a shared foundation. From this we can derive its various consequences.

This is both a matter of convincing each other of the logical soundness of the arguments, as well as a matter of organizing our body of shared knowledge. By understanding which facts are logical consequences of other more foundational, we can view the body of mathematical facts as a tree-like structure.

```{dot}
//| fig-height: 2
//| fig-width: 4

graph G {
    "Fact A" -- "Consequence AB";
    "Fact B" -- "Consequence AB";
    "Fact C" -- "Consequence ACD";
    "Fact D" -- "Consequence ACD";
    "Fact A" -- "Consequence ACD";
    "Fact C" -- "Consequence (AB)C"
    "Consequence AB" -- "Consequence (AB)C"
}
```

# Axiomatic Mathematics

Later when we return to study geometry, we will try to identify the "axioms" of geometry. These will be the foundational truths upon which every other fact of geometry follows. Indeed geometry isn't the only subject which can be constructed axiomatically, and we will see in later chapters that there are many other axiom systems. These include

-   Arithmetic
-   Real numbers
-   Set theory

In fact it will turn out that by organizing these subjects axiomatically will create an unexpected value! We will consider the possibility of removing or adding certain axioms, and see how this can produce new fields of mathematics!