---
title: "Two Examples"
---

In this section I want to introduce two arguments. If the lessons in this text are successful, the reader will understand the logic of these arguments in thorough detail.

# Algebra by Cases

::: {.callout-note title="Solve by Cases" appearance="minimal"}
Example:

Let $x$ be a number satisfying the equation

$$
(x-1)(x-2)=0
$$

We can easily see that $x=1$ is a solution of this equation. 

On the other hand, if $x\ne 1$ then $x-1\ne 0$. Therefore in this case we may divide both sides of the equation by $x-1$. When we do, we obtain the equation $x-2=0$ which implies $x=2$. 

Therefore there are two solutions: $x=1$ and $x=2$.

$\Box$
:::

::: {.callout-important title="Algebra Example Assumption Conclusion" appearance="minimal"}
Exercise:

Every argument starts from some assumptions. In the argument above, which sentences are assumptions?
::: x is a number & if x != 0

Also every argument ends in a conclusion. In the argument above, what is the conclusion of the argument?

Are there any key-words which seem to indicate an assumption? Are there key-words which indicate a conclusion?
:::

<!-- # One Even Prime 

In the argument below, we will prove that there is exactly one even prime number. The entire discussion will only consider natural numbers (i.e. positive whole numbers) since the idea of even and prime only make sense for natural numbers.[^1] That is to say, in this section, assume that every number in it, is a natural number.

[^1]: This is not entirely accurate. It is possible to talk about even integers, but we won't worry about this right now.

Recall that a number is even if it is divisible by 2. A number is prime if it is greater than 1, and its only divisors are "interesting". A divisor of a number is uninteresting if it is 1 or the number itself.

So for instance 3 is prime because it is greater than 1 and its only divisors are 1 and 3. But both 1 and 3 are uninteresting divisors of 3. On the other hand 4 is not prime because it has an interesting divisor: 2.

::: {.callout-important title="List Primes" appearance="minimal"}
Exercise:

List the first five prime numbers.
:::

To prove that there is one even prime, we will use an argument called "proof by contradiction". The strategy of a proof by contradiction is:

-   Assume a proposition which we think is actually false.

-   Use the proposition to prove a contradiction.

-   Therefore, the proposition must be false, because it leads to a contradiction. -->

Below is a proof that the sum of two positive numbers is always positive.  It starts from the assumption that this is *not* true.  That means that we start by assuming that some two positive numbers do *not* sum to a positive number.  We will then derive a contradiction, and therefore show that the assumption was false.

::: {.callout-note title="Positive Sum of Positives" appearance="minimal" }
For contradiction, assume that there are some two positive numbers which do not sum to a positive number.  Call these numbers $a$ and $b$.  Since they are positive, $0<a$ and $0<b$.  And since they do not sum to a positive number, then $a+b\le 0$.  

From $0<b$ we can infer $-b<0$ by subtracting $b$ from both sides.  Then from $a+b\le 0$ we can infer $a\le -b$.  But since we have $a\le -b$ and also $-b<0$ it follows that $a<0$.  Therefore $a$ is not positive.  

But we established earlier that $a$ is positive.  Hence we have a contradiction: $a$ is both positive and not positive.  

The assumption that "there are some two positive numbers which do not sum to a positive," led to a contradiction.  Therefore the assumption must be false.

This shows that any two positive real numbers must sum to a positive number.

$\Box$
:::

::: {.callout-important title="Negative Sum of Negatives" appearance="minimal"}
Use proof by contradiction to show that the sum of two negatives is always negative.
:::

::: {.callout-important title="Negative Irrational" appearance="minimal"}

A number is called **irrational** if it is not rational.  A number is rational if it can be expressed as $p/q$ where $p$ and $q$ are two integers and $q\ne 0$.  

Use proof by contradiction to show that if $x$ is irrational then so is $-x$.  

Hint:  Fill in the following argument, where blanks are marked with `%TODO`.

> Assume, for contradiction, that `%TODO`.  Then $-x$ can be expressed as $p/q$ where $p$ and $q$ are two integers, $q\ne 0$.  That is to say, $-x=p/q$.  But then 
> $$
> x = \%TODO
> $$ 
> But then $-p$ is an integer, and so is $q$, and $q\ne 0$ still.  Therefore $x$ is `%TODO`.  
>
> But this is a contradiction, since we now have that $x$ both is and isn't a rational number.  Therefore the assumption was false, which shows that $-x$ is irrational.  

:::

<!-- In particular, in the argument below we will assume that there are two even prime numbers. We will then show that this leads to a contradiction. Therefore, the conclusion is that there are **not** two even primes. -->

<!-- ::: {.callout-important title="Even Means Two Divides" appearance="minimal"}
Exercise:

1\.

Think for a minute about what "even" means. Try to give an intuitive definition.

------------------------------------------------------------------------

2\.

Mathematicians give a definition that is likely different from the one that you gave in response to the exercise above. A mathematician says that the number $p$ is even if there is a natural number $k$ such that $p=2k$.

Use the mathematician's definition of "even" to show that 10 is even.

------------------------------------------------------------------------

3\.

"Even" is really just one example of "divisibility". Give an intuitive definition of what it means for a number $q$ to divide another number $p$.

------------------------------------------------------------------------

4\.

Of course mathematicians define it differently. They say that the number $q$ divides $p$ if there is an integer $k$ such that $p=qk$.

Show that, according to the mathematician's definition, 5 divides 25.
:::

::: {.callout-note title="One Even Prime" style="background-color: #fff5fc" appearance="minimal"}
Example:

First notice that 2 is even because it can be divided by 2. Also 2 is prime because it is greater than 1, and its only divisors are 1 and 2 which are both uninteresting. Therefore there is *at least one* even prime number.

For the next part, we will show that there are **not** two even prime numbers. For an argument by contradiction, assume that there **are** two even prime numbers. 

Let $p$ be an even prime number other than 2.

Because $p$ is prime, then it is greater than 1. Because it is even, then there must exist some positive natural number $k$ such that $p=2k$. But this shows that, by definition, $p$ is divisible by 2. Since $p$ is not equal to 2, then this must mean that 2 is an interesting divisor. In turn, this means that $p$ is not prime.

But at the start we assumed that $p$ was prime, and therefore we have a contradiction: $p$ is both prime and not prime.

Since the assumption that "there is an even prime number other than 2" leads to a contradiction, then it must be false. Therefore we conclude that there is only one even prime number.

$\Box$
:::

::: {.callout-important title="Primes Mod Three" appearance="minimal"}
Exercise:

Prove that there is exactly one prime number which can be divided by 3. (Hint: The proof is almost exactly like the example for even primes above.)

Also prove that there are no primes which can be divided by 4. (Hint: Show that if a number can be divided by 4 then it can be divided by 2. Then use the fact that if a number can be divided by 4, then it cannot be equal to 2, and therefore has an interesting divisor. Note that this argument is totally different from the one above, and will *not* use proof by contradiction.)
::: -->